"""
export_service.py — Design kit export generators.
Produces .md, .pdf, .docx, and .zip exports using Jinja2 templates.
"""
import io
import json
import zipfile
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

TEMPLATE_DIR = Path(__file__).parent.parent.parent / "templates" / "exports"
env = Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)), autoescape=False)


def _build_context(sheet, blocks, pipeline_nodes) -> dict:
    """Build template context from project artifacts."""
    return {
        "problem": sheet.problem or "Not specified",
        "audience": sheet.audience or "Not specified",
        "mvp": sheet.mvp or "Not specified",
        "features": sheet.features or [],
        "tone": sheet.tone or "Not specified",
        "platform": sheet.platform or "Not specified",
        "tech_constraints": sheet.tech_constraints or "None",
        "success_metric": sheet.success_metric or "Not specified",
        "confidence_score": sheet.confidence_score,
        "blocks": [
            {
                "name": b.name,
                "description": b.description or "",
                "category": b.category,
                "priority": b.priority,
                "effort": b.effort,
                "is_mvp": b.is_mvp,
            }
            for b in blocks
        ],
        "mvp_blocks": [b for b in blocks if b.is_mvp],
        "v2_blocks": [b for b in blocks if not b.is_mvp],
        "pipeline": [
            {"layer": n.layer, "tool": n.selected_tool}
            for n in pipeline_nodes
        ],
    }


async def generate_markdown(sheet, blocks, pipeline_nodes) -> str:
    """Generate a Markdown export of the project design kit."""
    context = _build_context(sheet, blocks, pipeline_nodes)

    try:
        template = env.get_template("design_kit.md.j2")
        return template.render(**context)
    except Exception:
        # Fallback: generate inline
        lines = [
            f"# Design Kit",
            f"",
            f"## Problem",
            f"{context['problem']}",
            f"",
            f"## Target Audience",
            f"{context['audience']}",
            f"",
            f"## MVP Scope",
            f"{context['mvp']}",
            f"",
            f"## Features",
        ]
        for b in context["blocks"]:
            lines.append(f"- **{b['name']}** ({b['priority'].upper()}, {b['effort']}) — {b['description']}")

        lines.extend([
            f"",
            f"## Tech Stack",
        ])
        for p in context["pipeline"]:
            lines.append(f"- {p['layer']}: {p['tool']}")

        lines.extend([
            f"",
            f"## Constraints",
            f"{context['tech_constraints']}",
            f"",
            f"## Success Metric",
            f"{context['success_metric']}",
            f"",
            f"---",
            f"*Generated by Ide/AI | Confidence: {context['confidence_score']}%*",
        ])
        return "\n".join(lines)


async def generate_text(sheet, blocks, pipeline_nodes) -> str:
    """Generate a plain text export."""
    md = await generate_markdown(sheet, blocks, pipeline_nodes)
    # Strip markdown formatting for plain text
    text = md.replace("# ", "").replace("## ", "").replace("**", "").replace("*", "")
    text = text.replace("---", "=" * 40)
    return text


async def generate_pdf(sheet, blocks, pipeline_nodes) -> bytes:
    """Generate a PDF export of the project design kit using fpdf2."""
    from fpdf import FPDF

    context = _build_context(sheet, blocks, pipeline_nodes)

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 15, "Design Kit", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Problem
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Problem", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, context["problem"])
    pdf.ln(5)

    # Audience
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Target Audience", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, context["audience"])
    pdf.ln(5)

    # MVP
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "MVP Scope", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, context["mvp"])
    pdf.ln(5)

    # Features
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Features", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    for b in context["blocks"]:
        pdf.multi_cell(0, 6, f"  - {b['name']} ({b['priority'].upper()}, {b['effort']}) - {b['description']}")
    pdf.ln(5)

    # Tech Stack
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Tech Stack", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    for p in context["pipeline"]:
        pdf.cell(0, 6, f"  - {p['layer']}: {p['tool']}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Footer
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 10, f"Generated by Ide/AI | Confidence: {context['confidence_score']}%")

    return pdf.output()


async def generate_docx(sheet, blocks, pipeline_nodes) -> bytes:
    """Generate a DOCX export of the project design kit using python-docx."""
    from docx import Document
    from docx.shared import Pt

    context = _build_context(sheet, blocks, pipeline_nodes)

    doc = Document()

    doc.add_heading("Design Kit", level=0)

    doc.add_heading("Problem", level=1)
    doc.add_paragraph(context["problem"])

    doc.add_heading("Target Audience", level=1)
    doc.add_paragraph(context["audience"])

    doc.add_heading("MVP Scope", level=1)
    doc.add_paragraph(context["mvp"])

    doc.add_heading("Features", level=1)
    for b in context["blocks"]:
        p = doc.add_paragraph(style="List Bullet")
        run = p.add_run(f"{b['name']} ")
        run.bold = True
        p.add_run(f"({b['priority'].upper()}, {b['effort']}) — {b['description']}")

    doc.add_heading("Tech Stack", level=1)
    for p_item in context["pipeline"]:
        doc.add_paragraph(f"{p_item['layer']}: {p_item['tool']}", style="List Bullet")

    doc.add_heading("Constraints", level=1)
    doc.add_paragraph(context["tech_constraints"])

    doc.add_heading("Success Metric", level=1)
    doc.add_paragraph(context["success_metric"])

    # Footer
    footer = doc.add_paragraph()
    footer.add_run(f"Generated by Ide/AI | Confidence: {context['confidence_score']}%").italic = True

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


async def generate_zip(sheet, blocks, pipeline_nodes) -> bytes:
    """Generate a ZIP export containing all format exports."""
    md_content = await generate_markdown(sheet, blocks, pipeline_nodes)
    txt_content = await generate_text(sheet, blocks, pipeline_nodes)
    pdf_content = await generate_pdf(sheet, blocks, pipeline_nodes)
    docx_content = await generate_docx(sheet, blocks, pipeline_nodes)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("design-kit.md", md_content)
        zf.writestr("design-kit.txt", txt_content)
        zf.writestr("design-kit.pdf", pdf_content)
        zf.writestr("design-kit.docx", docx_content)

    return buf.getvalue()
